DELIMITER //

DROP FUNCTION IF EXISTS ConvertHexToUint32 //
CREATE FUNCTION ConvertHexToUint32(hexValue BINARY(4))
RETURNS BIGINT
DETERMINISTIC
BEGIN
    RETURN CAST(CONV(HEX(REVERSE(hexValue)), 16, 10) AS UNSIGNED);
END //

DROP FUNCTION IF EXISTS ConvertHexToUint16 //
CREATE FUNCTION ConvertHexToUint16(hexValue BINARY(2))
RETURNS BIGINT
DETERMINISTIC
BEGIN
    RETURN CAST(CONV(HEX(REVERSE(hexValue)), 16, 10) AS UNSIGNED);
END //

DROP FUNCTION IF EXISTS ConvertHexToUint8 //
CREATE FUNCTION ConvertHexToUint8(hexValue BINARY(1))
RETURNS BIGINT
DETERMINISTIC
BEGIN
    RETURN CAST(CONV(HEX(REVERSE(hexValue)), 16, 10) AS UNSIGNED);
END //

DELIMITER ;
